stages:
  - test
  - online-test
  - coverage
  - documentation

include:
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/gitlab-templates/test_templates.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/gitlab-templates/coverage.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/gitlab-templates/documentation.yml

# Disable GitLab CI's default cache policy of "pull-push"
# https://docs.gitlab.com/ee/ci/yaml/#cache-policy
# https://docs.gitlab.com/ce/ci/caching/index.html#disabling-cache-on-specific-jobs
cache: {}

variables:
  JULIA_IMAGE: 468665244580.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:0.6
  ONLINE: ""


"0.6 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_0_6

"0.6 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker

"0.6 (Linux, 32-bit)":
  tags:
    - linux
    - 32-bit
    - shell-ci
  extends: .test_shell_0_6

"1.0 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_0

"1.0 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_1_0

"1.0 (Linux, 32-bit)":
  tags:
    - linux
    - 32-bit
    - shell-ci
  extends: .test_shell_1_0

"Nightly (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_nightly

"Nightly (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_nightly

"Nightly (Linux, 32-bit)":
  tags:
    - linux
    - 32-bit
    - shell-ci
  extends: .test_shell_nightly

# Online test run as a separate stage to avoid running these expensive tests if the basic tests fail.
"Online Tests":
  stage: online-test
  tags:
    - linux
    - docker
    - ecr
    - batch
  variables:
    AWS_STACKNAME: aws-batch-manager-test
    ONLINE: "docker, batch"  # Runs the online tests for AWS Batch & Docker
  script:
    - source julia-ci export
    - export PATH="$PATH:/usr/local/bin"
    - unset SSL_CERT_DIR
    - ./julia-ci test
    - ./julia-ci coverage
  after_script:
    - ./julia-ci clean
    - sleep 5
    - "ACCOUNT_ID=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep -oP '(?<=\"accountId\" : \")[^\"]*(?=\")')"
    - "REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep -oP '(?<=\"region\" : \")[^\"]*(?=\")')"
    - docker rmi $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/aws-batch-manager-test:$(git rev-parse --short $CI_COMMIT_SHA)
  extends: .test_shell_0_6
